spring:
  application:
    name: store
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
dotenv:
  enabled: true

jwt:
  secret: ${JWT_SECRET}
  accessTokenExpiration: 7200
  refreshTokenExpiration: 604800
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}